SELECT p.STAMP_DATE, 
       p.PERSON_ID, 
       p.LAST_NAME, 
       p.FIRST_NAME, 
       p.MAIDEN_NAME, 
       p.NICK_NAME, 
       p.EMPLOYEE_ID, 
       c.ISO_COUNTRY_CODE,
       c.NAME AS COUNTRY_OF_BIRTH, 
       i.DISPLAY_NAME AS IMMIGRATION_STATUS
FROM [IMS].[dbo].[Person] AS p
LEFT OUTER JOIN [IMS].[dbo].[Country] AS c ON p.COUNTRY_OF_BIRTH = c.ISO_COUNTRY_CODE
LEFT OUTER JOIN [IMS].[dbo].[IMMIGRATION_STATUS] AS i ON p.IMMIGRATION_STATUS_ID = i.IMMIGRATION_STATUS_ID
WHERE p.[STAMP_DATE] > :sql_last_value