version: '2'
services:
  frag-sql:
    container_name: frag-sql
    build: ./sql
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Turk3yT1m3
    ports:
      - 1433:1433
    volumes:
      - sqldata:/var/opt/mssql
    stdin_open: true
  frag-elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: frag-elasticsearch1
    environment:
      - cluster.name=frag-search-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.enabled=true"
      # Need to change this to the specific origin's that are allowed.
      - "http.cors.allow-origin='*'"
      - "http.cors.allow-headers=Authorization"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  frag-elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: frag-elasticsearch2
    environment:
      - cluster.name=frag-search-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=frag-elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  frag-elasticsearch-head:
    image: mobz/elasticsearch-head:5
    container_name: frag-elasticsearch-head
    ports:
      - 9100:9100
  frag-logstash:
    container_name: frag-logstash
    build: ./logstash
    depends_on:
      - frag-sql
      - frag-elasticsearch1
    environment:
      - SQLSERVER_NAME=frag-sql
      - SQLSERVER_USER=sa
      - SQLSERVER_PASS=Turk3yT1m3
      - ELASTICSEARCH_NAME=192.168.1.2

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  sqldata:
    driver: local

networks:
  esnet:
    driver: bridge