version: '2'
services:
  sql:
    container_name: sql
    build: ./sql
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Turk3yT1m3
    ports:
      - 1433:1433
    volumes:
      - sqldata:/var/opt/mssql
    stdin_open: true
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: elasticsearch1
    environment:
      - cluster.name=search-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=elasticsearch1
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: elasticsearch2
    environment:
      - cluster.name=search-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=elasticsearch1
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    container_name: elasticsearch-head
    ports:
      - 9100:9100
  logstash:
    container_name: logstash
    build: ./logstash
    environment:
      - SQLSERVER_NAME=sql
      - SQLSERVER_USER=sa
      - SQLSERVER_PASS=Turk3yT1m3
      - ELASTICSEARCH_URL=192.168.1.2
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - XPACK_SECURITY_ENABLED =false
      - ELASTICSEARCH_URL=http://192.168.1.2:9200
      - xpack.monitoring.ui.container.elasticsearch.enabled=false

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  sqldata:
    driver: local

networks:
  esnet:
    driver: bridge