 FROM logstash:5

# ENV SQLSERVER_NAME
# ENV SQLSERVER_USER
# ENV SQLSERVER_PASS
# ENV ELASTICSEARCH_NAME

# Install base packages
RUN apt-get -y update \
 && apt-get install -y wget

RUN wget -O /tmp/sqljdbc_6.0.8112.100_enu.tar.gz https://download.microsoft.com/download/0/2/A/02AAE597-3865-456C-AE7F-613F99F850A8/enu/sqljdbc_6.0.8112.100_enu.tar.gz \
 && tar -C /opt -xzvf /tmp/sqljdbc_6.0.8112.100_enu.tar.gz

# Clean up apt-get
RUN apt-get remove -y wget \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY logstash.conf /bin/logstash/

RUN mkdir -p /usr/src/sql/
COPY ./sql/*.sql /usr/src/sql/

CMD ["-f", "/bin/logstash/logstash.conf"]