
# The official logstash image throws errors when running apt-get.
FROM docker.elastic.co/logstash/logstash:5.2.2
RUN rm -f /usr/share/logstash/pipeline/logstash.conf

# ENV SQLSERVER_NAME
# ENV SQLSERVER_USER
# ENV SQLSERVER_PASS
# ENV ELASTICSEARCH_URL

USER root

# Install base packages
RUN apt-get -y update \
 && apt-get install -y wget

RUN wget -O /tmp/sqljdbc_6.0.8112.100_enu.tar.gz https://download.microsoft.com/download/0/2/A/02AAE597-3865-456C-AE7F-613F99F850A8/enu/sqljdbc_6.0.8112.100_enu.tar.gz \
 && tar -C /opt -xzvf /tmp/sqljdbc_6.0.8112.100_enu.tar.gz

# Clean up apt-get
RUN apt-get remove -y wget \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY pipeline/ /usr/share/logstash/pipeline/
COPY config/ /usr/share/logstash/config/

COPY ./sql/*.sql /usr/src/sql/

USER logstash

CMD ["logstash", "-f", "/usr/share/logstash/pipeline/"]