FROM microsoft/mssql-server-linux:latest

# Set this so that it skips prompting you during the mssql-tools package install
ENV ACCEPT_EULA=Y

# Install curl inorder to get the microsoft packages
RUN apt-get -y update \
  && apt-get install -y curl apt-transport-https

# Install the mssql-tools package which contains sqlcmd and bcp utilities
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/msprod.list \
  && apt-get update \
  && apt-get install -y mssql-tools \
  && ln -sfn /opt/mssql-tools/bin/sqlcmd-13.0.1.0 /usr/bin/sqlcmd \
  && ln -sfn /opt/mssql-tools/bin/bcp-13.0.1.0 /usr/bin/bcp

# Update the locale for sqlcmd to work
RUN locale-gen en_US.UTF-8 \
 && update-locale

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy files used during startup
COPY restore-database.sh /usr/src/app/
COPY entrypoint.sh /usr/src/app/
COPY startup.sql /usr/src/app/

COPY Northwind.bak /tmp/

# Grant permissions for the import-data script to be executable
RUN chmod +x /usr/src/app/restore-database.sh

CMD /usr/src/app/entrypoint.sh