FROM microsoft/mssql-server-linux:latest

ENV ACCEPT_EULA "Y"
ENV SA_PASSWORD "pa$$w0rd"

RUN /opt/mssql/bin/sqlservr.sh

COPY Northwind.bak /tmp/


# Install base packages
RUN apt-get -y update \
 && apt-get install -y curl apt-transport-https

# Import the repository key
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/msprod.list

RUN apt-get -y update
RUN apt-get -y install mssql-tools unixodbc-dev

RUN locale-gen en_US
RUN locale-gen en_US.UTF-8

RUN update-locale

RUN rm /bin/sh && ln -sf /bin/bash /bin/sh
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc_profile
# RUN source ~/.bashrc

# RUN /bin/bash -c "source ~/.bashrc"

# RUN systemctl status mssql-server

# Restore the backup file
RUN /opt/mssql-tools/bin/sqlcmd -U sa -P pa$$w0rd -Q 'select * from sys.databases'


# RUN /bin/bash "/opt/mssql-tools/bin/sqlcmd -U sa -P pa$$w0rd -Q ""RESTORE DATABASE Northwind FROM DISK='/tmp/Northwind.bak'"""


